<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Copyright>Copyright © 2026 MegaPiggy</Copyright>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <NoWarn>MSB3270</NoWarn>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <Target Name="ReadModVersion" BeforeTargets="GetAssemblyVersion">
    <ReadLinesFromFile File="$(MSBuildProjectDirectory)\mod_meta.json">
      <Output TaskParameter="Lines" ItemName="ModMetaLines" />
    </ReadLinesFromFile>

    <PropertyGroup>
      <ModMetaJson>@(ModMetaLines, '')</ModMetaJson>
      <Version>$([System.Text.RegularExpressions.Regex]::Match('$(ModMetaJson)', '&quot;Version&quot;\s*:\s*&quot;([^&quot;]+)&quot;').Groups[1].Value)</Version>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="DredgeGameLibs" Version="1.5.2" />
    <PackageReference Include="HarmonyX" Version="2.10.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="Winch" Version="0.6.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="default_config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="mod_meta.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Assets\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="FishImageReplacer.csproj.user" />
  </ItemGroup>
</Project>
